name: Deploy Dist

on: #[push,workflow_dispatch]
    push:
        branches:
            - main
        paths-ignore:
            - '.github/workflows/*'
            - README.md
    workflow_dispatch:       
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Cache Dependencies
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}         #ubuntu-node-hashvalue

            - name: Install Dependencies
              run: npm ci

            - name: Run Tests
              run: npm run test

    build: 
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Cache Dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}         #ubuntu-node-hashvalue

            - name: Install Dependencies
              run: npm install ci

            - name: Build Project
              run: npm run build