name: Deploy Dist

on: [push,workflow_dispatch]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 20
            
            - name: Install Dependencies
              run: npm ci

            - name: Run Tests
              run: npm run test

    build: 
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Install Dependencies
              run: npm install ci

            - name: Build Project
              run: npm run build